### PR TITLE
Update to newest Teslamate Release + Small fix in Grafana config

### LINKED ISSUE #125: TeslaApi.Error / %{"error" => "Endpoint is only available on fleetapi
**Describe the bug**
Looks like TeslaMate is not able to get vehicles , using this add-on 

TeslaApi.Error / %{"error" => "Endpoint is only available on fleetapi.

2024-02-03 12:12:04.901 [info] Migrations already up
2024-02-03 12:12:08.727 [info] System Info: Erlang/OTP 26 (jit)
2024-02-03 12:12:08.727 [info] Version: 1.28.2
2024-02-03 12:12:09.950 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (1179.219 ms)
2024-02-03 12:12:09.950 [info] Refreshed api tokens
2024-02-03 12:12:09.964 [info] Scheduling token refresh in 6 h
2024-02-03 12:12:09.970 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
2024-02-03 12:12:09.971 [info] Access TeslaMateWeb.Endpoint at http://localhost
2024-02-03 12:12:10.702 [info] GET https://owner-api.teslamotors.com/api/1/vehicles -> 412 (729.845 ms)
2024-02-03 12:12:10.702 [warning] TeslaApi.Error / %{"error" => "Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info", "error_description" => "", "response" => nil}
2024-02-03 12:12:10.702 [warning] Could not get vehicles: :unknown
2024-02-03 12:12:11.376 [info] MQTT connection has been established

**Steps to reproduce**

1.
2.

**Screenshots**

### PR DESCRIPTION
**Pull request by vh2002**
No active testing done, assuming just an realease update is enough when checking the original changelog.

Closes #125 as it is fixed in the original repo.

### CODE REVIEW

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
PR branch does not have access to secrets

Thank you for this PR. I will pull into a local branch and run

**Comment by vh2002** [comment]
One question regarding the PRs. As the secrets are needed to run the checks successful, what is the point of even having PRs and is there a potential way around?

**Comment by shivaagarwal1** [comment]
> PR branch does not have access to secrets
> 
> Thank you for this PR. I will pull into a local branch and run

Hi Matt. Apologies for pushing it, but do you know when you will be able to update the add-on? I am checking the page every 5 mins like a moron :p

**Review by matt-FFFFFF — APPROVED** [review]

**Comment by matt-FFFFFF** [comment]
> One question regarding the PRs. As the secrets are needed to run the checks successful, what is the point of even having PRs and is there a potential way around?

Because I haven't skipped the docker login & push to docker hub steps for PRs from a fork. This is all possible of course but it's just time.

At the beginning it was just me maintaining this so it wasn't an issue.

**Pull request merged**
