### PR TITLE
feat: tmupgrade

### PR DESCRIPTION
**Pull request by matt-FFFFFF**

### CODE REVIEW

**Comment by OrangeBean** [comment]
Thanks @matt-FFFFFF 
I also sent another one for [repository](https://github.com/matt-FFFFFF/hassio-addon-repository/pull/28)

**Comment by matt-FFFFFF** [comment]
The release automation does this, so no need.

**Comment by OrangeBean** [comment]
nice 👍

**Comment by matt-FFFFFF** [comment]
I manually run the release workflow in .github/workflows/release.yml

**Pull request merged**
