### PR TITLE
Add Ingress Support

### PR DESCRIPTION
**Pull request by tcm0116**
This pull request adds the ability to utilize Ingress to access the TeslaMate web interface.

All of the features of the web interface appear to work with the exception of the navigation links at the top of the Settings and Geo-Fence pages. They appear to be generated via a live view and are hard-linked to the root no matter what sub-filters I try. As part of a live view, I would have thought that setting the path in the releases.exs would have resulted in the desired behavior, but apparently not.

A good next step would be to add the ability to set the URL path option via an environment variable similarly to the other config values. From there, the paths that appear to be hard-coded based on the root within TeslaMate (e.g. the ones being modified via the sub-filters) would then need to be updated to utilize that URL path instead of assuming a path of "/".

I also included the development environment I ended up using (from https://github.com/issacg/hassio-addon-devcontainer) to work on this as it was very handy to be able to spin up a local instance of Home Assistant with the add-on ready to install. I did remove the image setting from the config.json to allow Home Assistant to build the add-on dynamically (it took me a little while to figure out why none of my changes were being incorporated into the add-on image :-D). That can be removed, if desired.

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
Hi - this is awesome - thanks for you work, I will take a look and validate over the next few days. Thanks also for the devcontainer stuff - really cool.

**Comment by tcm0116** [comment]
I think I know why it's not working. The Dockerfile uses the s6-overlay-amd64.tar.gz version of the s6 overlay image. I'm assuming I'd want the arm version and not the amd64 version when running on the RPi. I took a look at the GitHub workflow that is used to build the images, thinking that it would change that file name, but it doesn't. How is the correct architecture for that for selected in your current workflow?

**Comment by matt-FFFFFF** [comment]
> I think I know why it's not working. The Dockerfile uses the s6-overlay-amd64.tar.gz version of the s6 overlay image. I'm assuming I'd want the arm version and not the amd64 version when running on the RPi. I took a look at the GitHub workflow that is used to build the images, thinking that it would change that file name, but it doesn't. How is the correct architecture for that for selected in your current workflow?

Thanks - good find and I think you're right. The builds are performed using the matrix build function of GitHub Actions:

https://github.com/matt-FFFFFF/hassio-addon-teslamate/blob/0a82b9eba8db7f1ffe604ac6adcd7da2312b782a/.github/workflows/teslamate.yml#L23

There is an env variable set for each of the builds. This will need to be mapped to the correct s6 overlay release - maybe using an ARG declaration on the docker build. I'll take a look.

**Comment by tcm0116** [comment]
Interestingly, it works just fine if I install the addon from your repository, so it seems that the images created with your workflow use the correct architecture for the s6 overlay. Since I'm running the addon locally, and have it configured to build the image rather than download it, I'm assuming I'll need to adjust the Dockerfile to use the correct architecture for the s6 overlay. Where I'm confused is that I don't see how that happens with your GitHub workflow. I see that you're running the matrix build, but it's not clear how the architecture of the s6 overlay is changed.

**Comment by matt-FFFFFF** [comment]
> Interestingly, it works just fine if I install the addon from your repository, so it seems that the images created with your workflow use the correct architecture for the s6 overlay. Since I'm running the addon locally, and have it configured to build the image rather than download it, I'm assuming I'll need to adjust the Dockerfile to use the correct architecture for the s6 overlay. Where I'm confused is that I don't see how that happens with your GitHub workflow. I see that you're running the matrix build, but it's not clear how the architecture of the s6 overlay is changed.

I agree, I think this is a bug and needs fixing. No idea why it works using the public repo - I note that the arch _nearly_ matches up with the s6 releases. It's only armv7->arm that is different.

**Comment by matt-FFFFFF** [comment]
Couple of commits to support the correct s6 overlay release

**Comment by matt-FFFFFF** [comment]
Build fails due to no access to secrets, tested in another branch and s6 changes work - will merge into main and get the dev images built.

**Comment by matt-FFFFFF** [comment]
This is now live with v0.5.0 (after much faffing with release automation 😄)

Thanks again for your work!

**Comment by tcm0116** [comment]
I just updated, but ingress isn't working. The following shows up in the log:
```
sed: /opt/app/releases/*/releases.exs: No such file or directory
```
I wonder if the wildcard doesn't work on the RPi for some reason.

**Comment by matt-FFFFFF** [comment]
Releases.exs doesn’t exist. There is a runtime.exs. Maybe there has been a change with 1.21

Matt
________________________________

**Comment by matt-FFFFFF** [comment]
I had the same error, trying to debug it now

**Comment by matt-FFFFFF** [comment]
#12 has fixed it I think, use the `dev` tag to test

**Comment by tcm0116** [comment]
Looking at the TeslaMate repo, it does look like releases.exs was renamed to runtime.exs in 1.21. As such, I think #12 should work. Thanks for looking into it!

**Comment by tcm0116** [comment]
Is there a way to use the dev tag when using your repo?

**Comment by matt-FFFFFF** [comment]
I pulled the dev image and then tagged it locally:

```bash
docker tag mattffffff/teslamate-amd64:dev mattffffff/teslamate-amd64:0.5.0
```

But, have just released the fix now: https://github.com/matt-FFFFFF/hassio-addon-teslamate/releases/tag/v0.5.1

**Comment by tcm0116** [comment]
v0.5.1 looks like it's working now.

I noticed that you left the ability to enable the port for export. With the changes that were made, trying to access the port won't work correctly because of the change to the base path. You might want to consider removing the ability to share that port.

**Comment by matt-FFFFFF** [comment]
Thanks for confirming. I have removed the ports from the config.json but the option still remains in the HA UI for some reason.

If you click the ‘reset to defaults’ button then the options will disappear.

Matt
________________________________

**Comment by tcm0116** [comment]
Resetting the defaults did the trick!

**Pull request merged**
