### PR TITLE
update to teslamate 1.25.0

### LINKED ISSUE #49: bump version?
Hello again,

I would ask if you can bump the teslamate version to latest, thanks!

### PR DESCRIPTION
**Pull request by coreGreenberet**
closes #49

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
Hi, thanks for the PR. Sorry I've been away for a few days. I'll get to this tomorrow!

**Comment by coreGreenberet** [comment]
No Problem =) It wasn't a complicated change =D

**Comment by ohadlevy** [comment]
bump :) thanks!

**Comment by matt-FFFFFF** [comment]
Closing and implementing in #52 as third party PRs have no access to secrets

**Pull request closed without merging**
